use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use toml::Table;
use toml::Value;

pub(crate) fn run(
    action: Option<&str>,
    workspace_root: &Path,
    output: &Path,
) -> Result<(), String> {
    let generated = render(workspace_root)?;
    match action {
        Some("generate") => {
            write_if_changed(output, generated.as_bytes())?;
            println!("generated {}", output.display());
            Ok(())
        }
        Some("check") => {
            let current = fs::read_to_string(output)
                .map_err(|error| format!("cannot read {}: {error}", output.display()))?;
            if current != generated {
                return Err(format!(
                    "{} is stale; run `cargo run -p xtask -- bazel-deps generate`",
                    output.display()
                ));
            }
            println!("Cargo-to-Bazel workspace dependencies are current");
            Ok(())
        }
        _ => Err("usage: cargo run -p xtask -- bazel-deps <generate|check>".to_owned()),
    }
}

fn render(workspace_root: &Path) -> Result<String, String> {
    let workspace_manifest_path = workspace_root.join("Cargo.toml");
    let workspace_manifest = read_manifest(&workspace_manifest_path)?;
    let workspace = required_table(&workspace_manifest, "workspace", &workspace_manifest_path)?;
    let members = workspace
        .get("members")
        .and_then(Value::as_array)
        .ok_or_else(|| "workspace Cargo.toml has no members array".to_owned())?;
    let workspace_dependencies = workspace
        .get("dependencies")
        .and_then(Value::as_table)
        .cloned()
        .unwrap_or_default();

    let mut member_labels = BTreeMap::new();
    let mut manifests = BTreeMap::new();
    for member in members {
        let member = member
            .as_str()
            .ok_or_else(|| "workspace member must be a string".to_owned())?;
        let directory = workspace_root.join(member);
        let canonical_directory = fs::canonicalize(&directory)
            .map_err(|error| format!("cannot resolve {}: {error}", directory.display()))?;
        let package = format!("webp-rs/{member}");
        member_labels.insert(canonical_directory, format!("//{package}"));
        manifests.insert(package, read_manifest(&directory.join("Cargo.toml"))?);
    }

    let mut dependencies = BTreeMap::new();
    for (package, manifest) in manifests {
        let package_directory = workspace_root.join(package.trim_start_matches("webp-rs/"));
        let labels = path_dependencies(
            manifest.get("dependencies").and_then(Value::as_table),
            &package_directory,
            workspace_root,
            &workspace_dependencies,
            &member_labels,
        )?;
        if !labels.is_empty() {
            dependencies.insert(package, labels);
        }
    }

    let mut output = String::from(
        "# @generated by `cargo run -p xtask -- bazel-deps generate`\n\
         # Do not edit manually.\n\n\
         \"\"\"Cargo workspace dependency labels omitted by crate_universe.\"\"\"\n\n\
         _WORKSPACE_DEPS = {\n",
    );
    for (package, labels) in dependencies {
        output.push_str(&format!("    \"{package}\": [\n"));
        for label in labels {
            output.push_str(&format!("        \"{label}\",\n"));
        }
        output.push_str("    ],\n");
    }
    output.push_str(concat!(
        "}\n\n",
        "def workspace_deps(package_name = None):\n",
        "    \"\"\"Returns direct workspace path dependencies for a Cargo package.\"\"\"\n",
        "    if package_name == None:\n",
        "        package_name = native.package_name()\n",
        "    return _WORKSPACE_DEPS.get(package_name, [])\n",
    ));
    Ok(output)
}

fn path_dependencies(
    dependencies: Option<&Table>,
    package_directory: &Path,
    workspace_root: &Path,
    workspace_dependencies: &Table,
    member_labels: &BTreeMap<std::path::PathBuf, String>,
) -> Result<Vec<String>, String> {
    let mut labels = Vec::new();
    for (name, dependency) in dependencies.into_iter().flatten() {
        let Some(table) = dependency.as_table() else {
            continue;
        };
        let (base, path) = if let Some(path) = table.get("path").and_then(Value::as_str) {
            (package_directory, path)
        } else if table.get("workspace").and_then(Value::as_bool) == Some(true) {
            let Some(path) = workspace_dependencies
                .get(name)
                .and_then(Value::as_table)
                .and_then(|dependency| dependency.get("path"))
                .and_then(Value::as_str)
            else {
                continue;
            };
            (workspace_root, path)
        } else {
            continue;
        };
        let dependency_path = base.join(path);
        let canonical_dependency = fs::canonicalize(&dependency_path)
            .map_err(|error| format!("cannot resolve {}: {error}", dependency_path.display()))?;
        let label = member_labels.get(&canonical_dependency).ok_or_else(|| {
            format!(
                "path dependency {name} at {} is not a workspace member",
                dependency_path.display()
            )
        })?;
        labels.push(label.clone());
    }
    labels.sort();
    labels.dedup();
    Ok(labels)
}

fn read_manifest(path: &Path) -> Result<Table, String> {
    let input = fs::read_to_string(path)
        .map_err(|error| format!("cannot read {}: {error}", path.display()))?;
    toml::from_str(&input).map_err(|error| format!("invalid {}: {error}", path.display()))
}

fn required_table<'a>(table: &'a Table, key: &str, path: &Path) -> Result<&'a Table, String> {
    table
        .get(key)
        .and_then(Value::as_table)
        .ok_or_else(|| format!("{} has no [{key}] table", path.display()))
}

fn write_if_changed(path: &Path, bytes: &[u8]) -> Result<(), String> {
    if fs::read(path).ok().as_deref() == Some(bytes) {
        return Ok(());
    }
    fs::write(path, bytes).map_err(|error| format!("cannot write {}: {error}", path.display()))
}

#[cfg(test)]
#[path = "bazel_deps_tests.rs"]
mod tests;
