#![forbid(unsafe_code)]
//! VP8 lossy WebP decoder primitives.

mod bitstream;
mod coefficients;
mod encoder;
mod entropy;
mod frame;
mod intra;
mod loop_filter;
mod partition;
mod quantization;
mod reconstruction;
#[cfg(test)]
mod test_support;
mod transform;

pub use bitstream::BoolDecoder;
pub use bitstream::BoolEncodeError;
pub use bitstream::BoolEncoder;
pub use coefficients::COEFFICIENT_ZIGZAG;
pub use encoder::Vp8DcMacroblockCoefficients;
pub use encoder::Vp8EncodeError;
pub use encoder::Vp8SourceYuv;
pub use encoder::encode_dc_predicted_key_frame_with_quantizer;
pub use encoder::encode_dc_predicted_macroblock_key_frame;
pub use encoder::encode_dc_predicted_macroblock_key_frame_with_quantizer;
pub use encoder::encode_neutral_key_frame;
pub use encoder::quantize_dc_macroblock;
pub use encoder::rgba_to_yuv420;
pub use entropy::CoefficientBlockType;
pub use entropy::CoefficientEncodeError;
pub use entropy::CoefficientProbabilities;
pub use entropy::DecodedCoefficients;
pub use entropy::MacroblockResiduals;
pub use entropy::ResidualContext;
pub use entropy::decode_coefficients;
pub use entropy::decode_intra_residuals;
pub use entropy::encode_coefficients;
pub use frame::Vp8YuvImage;
pub use frame::decode_intra_frame;
pub use intra::ChromaMode;
pub use intra::Intra4Mode;
pub use intra::Intra16Mode;
pub use intra::IntraMacroblock;
pub use intra::LumaMode;
pub use intra::parse_intra_mode_row;
pub use loop_filter::LoopFilterStrength;
pub use loop_filter::derive_loop_filter_strengths;
pub use loop_filter::filter_normal_edge;
pub use loop_filter::filter_simple_edge;
pub use partition::FilterHeader;
pub use partition::FirstPartitionHeader;
pub use partition::PartitionLayout;
pub use partition::SegmentHeader;
pub use partition::TokenPartition;
pub use partition::Vp8Header;
pub use partition::parse_partition_layout;
pub use partition::parse_riff_payload;
pub use quantization::DequantizationMatrix;
pub use quantization::QuantizationHeader;
pub use quantization::derive_dequantization;
pub use quantization::quantize_block;
pub use reconstruction::DequantizedMacroblock;
pub use reconstruction::MacroblockPixels;
pub use reconstruction::MacroblockPredictionEdges;
pub use reconstruction::MacroblockSpatialResidues;
pub use reconstruction::add_residue_and_clip;
pub use reconstruction::combine_macroblock_prediction;
pub use reconstruction::dequantize_macroblock;
pub use reconstruction::inverse_transform_macroblock;
pub use reconstruction::predict_intra4_block;
pub use reconstruction::predict_intra4_macroblock;
pub use reconstruction::predict_intra16_macroblock;
pub use reconstruction::reconstruct_intra_macroblock;
pub use transform::forward_dct_4x4;
pub use transform::forward_dct_4x4_i32;
pub use transform::forward_wht_4x4;
pub use transform::forward_wht_4x4_i32;
pub use transform::inverse_dct_4x4;
pub use transform::inverse_dct_4x4_i32;
pub use transform::inverse_wht_4x4;
pub use transform::inverse_wht_4x4_i32;
