# @generated by `cargo run -p xtask -- bazel-deps generate`
# Do not edit manually.

"""Cargo workspace dependency labels omitted by crate_universe."""

_WORKSPACE_DEPS = {
    "webp-rs/alpha": [
        "//webp-rs/core",
        "//webp-rs/vp8l-literal",
    ],
    "webp-rs/animation": [
        "//webp-rs/core",
    ],
    "webp-rs/container": [
        "//webp-rs/core",
    ],
    "webp-rs/vp8": [
        "//webp-rs/core",
    ],
    "webp-rs/vp8l": [
        "//webp-rs/core",
    ],
    "webp-rs/vp8l-color-cache": [
        "//webp-rs/core",
        "//webp-rs/vp8l-entropy",
    ],
    "webp-rs/vp8l-entropy": [
        "//webp-rs/core",
    ],
    "webp-rs/vp8l-huffman": [
        "//webp-rs/core",
    ],
    "webp-rs/vp8l-indexing": [
        "//webp-rs/vp8l-transform",
    ],
    "webp-rs/vp8l-literal": [
        "//webp-rs/core",
        "//webp-rs/vp8l",
        "//webp-rs/vp8l-color-cache",
        "//webp-rs/vp8l-color-transform",
        "//webp-rs/vp8l-entropy",
        "//webp-rs/vp8l-huffman",
        "//webp-rs/vp8l-indexing",
        "//webp-rs/vp8l-transform",
    ],
    "webp-rs/webp": [
        "//webp-rs/alpha",
        "//webp-rs/animation",
        "//webp-rs/container",
        "//webp-rs/core",
        "//webp-rs/vp8",
        "//webp-rs/vp8l",
        "//webp-rs/vp8l-literal",
    ],
}

def workspace_deps(package_name = None):
    """Returns direct workspace path dependencies for a Cargo package."""
    if package_name == None:
        package_name = native.package_name()
    return _WORKSPACE_DEPS.get(package_name, [])
