#!/bin/sh
# Generate the committed integrity lock for the selected upstream vectors.
set -eu

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
corpus=${1:-third_party/corpus/libwebp-test-data}
selection="$repo_root/tests/corpora/libwebp-test-data-smoke-v1.txt"
output="$repo_root/tests/corpora/libwebp-test-data-smoke-v1.sha256"

if [ ! -d "$corpus/.git" ]; then
    printf '%s\n' "error: $corpus is not a Git checkout; run tools/fetch-libwebp-test-data.sh" >&2
    exit 1
fi

revision=$(git -C "$corpus" rev-parse HEAD)
temporary="$output.tmp"
{
    printf '%s\n' "# Generated by tools/update-upstream-smoke-lock.sh; do not edit."
    printf '%s\n' "# revision: $revision"
    while IFS= read -r fixture || [ -n "$fixture" ]; do
        case "$fixture" in
            '' | \#*) continue ;;
        esac
        file="$corpus/$fixture"
        if [ ! -f "$file" ]; then
            printf '%s\n' "error: missing selected upstream vector $file" >&2
            exit 1
        fi
        sha=$(shasum -a 256 "$file" | awk '{print $1}')
        printf '%s  %s\n' "$sha" "$fixture"
    done < "$selection"
} > "$temporary"
mv "$temporary" "$output"
printf '%s\n' "updated $output for $revision"
